language: java
sudo: false
install: true

jdk:
  # SonarQube 5.6 LTS requires Java 8
  - oraclejdk8

script: 
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

before_cache:
  - rm -rf $HOME/.m2/repository/com/sonarsource/it/clirr

addons:
  apt:
    packages:
      - oracle-java8-installer
