language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script: 
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

before_cache:
  - rm -rf $HOME/.m2/repository/com/sonarsource/it/clirr

notifications:
  email: false
